### ISSUE TITLE
Tiny fraction of data missed after synchronize_data

### ISSUE THREAD

**Issue by jfinzel** [2ndQuadrant/pglogical#64] opened 2016-12-06 19:33 UTC
In general, we have had this happen rarely, though often enough for it to be a bother (2 or 3 times in a few days).

I just added dozens of tables to replication on provider with synchronize_date = true.  All table were perfectly synchronized except for one table, in which there are 2 missing rows out of 450000.  There were zero errors or warnings in the logs.

I have also had this happen once before for a table with over 1 million rows in which 1 row was missing after sync.

Also, the show_subscription_table is showing this table as "synchronized" despite this issue.

There seems to be a possibility of missing data in the initial sync perhaps due to concurrent write going on at the moment of COPY or some such thing.  Have you seen this behavior before?

**Comment by ringerc** [comment] 2016-12-07 07:21
On 7 December 2016 at 03:33, Jeremy Finzel <notifications@github.com> wrote:
>
> I just added dozens of tables to replication on provider with
> synchronize_date = true. All table were perfectly synchronized except for
> one table, in which there are 2 missing rows out of 450000. There were zero
> errors or warnings in the logs.
>
I definitely have not seen reports of this before, and it's concerning.

The resync code goes to considerable lengths to ensure that it uses a
logical-decoding-provided snapshot to copy the initial data from, and
resumes apply of the data exactly at the end of that snapshot. There must
be an oversight somewhere, but it's not immediately clear how this could
come about, but this sounds likely to somehow be a race between commit and
the standby to decoding switchover.

Would I be correct in guessing that you do a lot of transactions that do
small inserts or updates, one or two rows? Very frequently?

It'd be interesting if you're able to set up a test DB with pglogical,
start pgbench, and resync the tables, then see if there's any such
discrepancy again. Possibly over a number of runs.


-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by jfinzel** [comment] 2017-01-18 19:07
It is indeed on tables with several small transactions running constantly, usually doing inserts.

I had this happen again today.  I can tell you one thing about it, perhaps interesting.  It has only happened so far as I know when I run `alter_subscription_resynchronize_table` on several tables at once.  And it is usually a big table (10+ million).

When I run `alter_subscription_resynchronize_table` on a single table, I've never had it happen.

Next time this happens I will try to determine if the missing records are on the head or tail end of the transaction.

**Comment by jfinzel** [comment] 2017-01-18 20:24
Okay, I can confirm that the issue also happens when I just do 1 synchronize at a time.  I just did one, and 4 records were missing with timestamps on the provider that are right during the sync time.

Provider records:
```
  id   |         changed_at
--------+----------------------------
 183062 | 2017-01-18 19:46:45.633849
 183061 | 2017-01-18 19:46:45.634772
 183060 | 2017-01-18 19:44:53.58376
 183059 | 2017-01-18 19:44:53.57768
 183058 | 2017-01-18 19:44:47.572308
 183057 | 2017-01-18 19:44:47.55901
 183056 | 2017-01-18 19:43:02.120821
(7 rows)
```

Subscriber records:
```
   id   |         changed_at
--------+----------------------------
 183062 | 2017-01-18 19:46:45.633849
 183061 | 2017-01-18 19:46:45.634772
 183056 | 2017-01-18 19:43:02.120821
(3 rows)
```

Subscriber logs during resync:
```
2017-01-18 13:44:55.618 CST,,,97413,,587fc5b7.17c85,1,,2017-01-18 13:44:55 CST,19/0,0,LOG,00000,"starting sync of table foo.table for subscriber subscriber1",,,,,,,,,"pglogical sync table 1010546:808311490"
2017-01-18 13:44:55.660 CST,,,97416,"10.7.198.107:56631",587fc5b7.17c88,1,"",2017-01-18 13:44:55 CST,,0,LOG,00000,"connection received: host=0.0.0.0 port=0",,,,,,,,,""
2017-01-18 13:44:55.673 CST,"foo","foo",97416,"10.7.198.107:56631",587fc5b7.17c88,2,"authentication",2017-01-18 13:44:55 CST,22/1675,0,LOG,00000,"connection authorized: user=foo database=foo SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, compression=on)",,,,,,,,,""
2017-01-18 13:44:59.674 CST,"foo","foo",97416,"10.7.198.107:56631",587fc5b7.17c88,3,"idle",2017-01-18 13:44:55 CST,,0,LOG,00000,"disconnection: session time: 0:00:04.014 user=foo database=foo host=10.7.198.107 port=56631",,,,,,,,,"subscriber1_copy"
2017-01-18 13:44:59.731 CST,,,97413,,587fc5b7.17c85,2,,2017-01-18 13:44:55 CST,19/0,0,LOG,00000,"pglogical sync finished processing; replayed to 347/36F245E8 of required 347/36F245E8",,,,,,,,,"pglogical sync table 1010546:808311490"
2017-01-18 13:44:59.750 CST,,,97413,,587fc5b7.17c85,3,,2017-01-18 13:44:55 CST,19/0,0,LOG,00000,"finished sync of table foo.table for subscriber subscriber1",,,,,,,,,"pglogical sync table 1010546:808311490"
2017-01-18 13:44:59.750 CST,,,97413,,587fc5b7.17c85,4,,2017-01-18 13:44:55 CST,19/0,0,LOG,00000,"sync worker [97413] at slot 9 generation 109 detaching cleanly",,,,,,,,,"pglogical sync table 1010546:808311490"
```

**Comment by ringerc** [comment] 2017-01-20 03:53
This is really interesting. It *shouldn't* be able to happen, because we
create a new replication slot for the sync and it exports a snapshot that
we dump. Every tuple should be in exactly one of the snapshot or the
replication change-stream.

Somehow the snapshot and change-stream are both missing needed tuples,
pglogical_output is filtering them out, or the pglogical downstream is
silently failing to apply them.

I'd be interested in a self contained script that could reproduce this -
fires up a workload then syncs a table and tests to see whether the result
matches on both sides. I don't expect to get time to write one myself soon
though.

It'd be extremely interesting to determine whether the same issue can be
reproduced using the test_decoding plugin, by applying a workload, creating
a slot with a snapshot, dumping the table from the snapshot, then using
pg_recvlogical to capture the start of the stream. If the "hole" can appear
in this case too, i.e. there are tuples missing from both the dump and
change-stream, we know it's not a pglogical problem. If we can't reproduce
it this way it tends to point toward pglogical.

Is there anything unusual, different or non-default about your master's
configuration? Do you use 2-phase commit? SERIALIZABLE xacts? ... ? It
*shouldn't* matter, but clearly _something_ is wrong. The ideal thing would
be to achieve a minimal reproducible test case here.

**Comment by jfinzel** [comment] 2017-01-20 16:27
I'm not sure I have time at the moment to reproduce this, only to say that it is now happening quite frequently.  It just happened upon an initial setup on adding a subscription with `synchronize_data = true`.  3 of 5 tables had a handful of records missing from updates during the sync.

**Comment by ringerc** [comment] 2017-03-01 08:57
@PJMODOS has identified a number of issues with the logical decoding snapshot builder in PostgreSQL. Fixes will be in coming point release(s) of PostgreSQL. It is extremely likely that these PostgreSQL bugs are the cause of the issues here, but I'll leave this open until we've confirmed that.

**Comment by PJMODOS** [comment] 2017-05-06 17:38
The PostgreSQL minor releases that are due next week should finally have fixes for this.

**Comment by eulerto** [comment] 2021-04-19 22:22
I tried to reproduce this issue without success (I'm using Postgres 11.11 + pglogical 2.3.3). Since there are [numerous fixes related to logical decoding](https://why-upgrade.depesz.com/show?from=9.6&to=9.6.21&keywords=logical+decoding) along the years, one of them could probably fix this issue. If this is still an issue, open a new issue and add a reference to this issue.

**Closed by eulerto** 2021-04-19 22:22 UTC
