### ISSUE TITLE
Column and row filtering not working

### ISSUE THREAD

**Issue by unotech001** [2ndQuadrant/pglogical#133] opened 2017-10-13 12:00 UTC
I have install Pglogical2.0 and try to replicate the data by column filter and row filter also. we run the below query for column filter on provider:
select pglogical.replication_set_add_table( 'repset','patientdtl', true, columns := '{pat_id,pat_age}');
The above query executed successfully but when we checked on subscriber the data is replicated columnwise or not, it wasn't. and same happened for row filter also.

PostgreSQL version is 9.5

Can anyone provide me solution?

**Comment by ringerc** [comment] 2017-10-17 01:57
Please provide a complete, self-contained example showing all statements and steps.

**Comment by unotech001** [comment] 2017-10-17 06:13
First we created 'dms' database(postgres 9.5) on both which have patientdtl table contain 3 columns as above:
1.pat_id int primary key
2.pat_name char(50)
3.pat_age int

Now we want to replicate only pat_id and pat_age columns or pat_id > 2 condition on subscriber but after follow below procedure it can't worked for us.
ALL data from patientdtl table is replicated as end result.

On provider :-

1. CREATE EXTENSION pglogical;

2. SELECT pglogical.create_node('provider1', 'host=provider ip  port=5432 dbname=dms                   user=postgres ');

3.created replication sets and add tables to them

select pglogical.create_replication_set( 'replication_set', true,true,true,true);

select pglogical.replication_set_add_table( 'replication_set','patientdtl', true,columns:='{pat_id,pat_age}');
OR
select pglogical.replication_set_add_table( 'replication_set','patientdtl', true,row_filter := 'pat_id > 2');

On Subscriber :-
1.CREATE EXTENSION pglogical;

2.SELECT pglogical.create_node('subscriber', 'host=subscriber IP  port=5432 dbname=dms user=postgres ');

3.SELECT pglogical.create_subscription(subscription_name     := 'subscription1',provider_dsn := 'host= privider ip port=5432 dbname=dms user=postgres',synchronize_structure := false,synchronize_data := true);

4.pglogical.alter_subscription_resynchronize_table('subcsription1','patientdtl');


Please helppp as soon as possible  !!!

**Comment by ringerc** [comment] 2017-10-17 06:26
Thanks for the details.

In pglogical 2.0's `pglogical_sync.c`, pglogical produces a `COPY` query like:

     "COPY (SELECT %s FROM pglogical.table_data_filtered(NULL::%s, %s::regclass, ARRAY[%s])) "

Can you confirm what gets run by enabling `log_statement = 'all'` on both nodes, then `SELECT pg_reload_conf()` on both nodes, or restart them? Then re-run `pglogical.alter_subscription_resynchronize_table('subcsription1','patientdtl')` ?

> Please helppp as soon as possible !!!

I can't guarantee any timelines for updates and fixes. That's why we have support services, which I must prioritise.

**Comment by unotech001** [comment] 2017-10-17 10:17
Thanks for your reply.

We have tried by your steps but still not getting correct result.

Can you check from your side by following our given steps and your given step if needed.?

**Comment by ringerc** [comment] 2017-10-18 01:50
I'm not making suggestions to help you get a correct result, I'm asking you to repeat your steps with some additional settings, and send me the resulting log output so I can hopefully diagnose the issue.

I don't have the time to try to reproduce this via manual steps right now.

**Comment by unotech001** [comment] 2017-10-18 07:08
Thanks for reply.

We have tried again with all steps but desired output is not coming.

Column wise replication or row filtering not working on pglogical 2.0 with postgresql 9.5

**Comment by unotech001** [comment] 2017-10-23 09:22
![Uploading Access snap shot.png…]()

**Comment by ringerc** [comment] 2017-10-23 09:34
I don't understand why you're closing the issue if it's not working.

But I also don't understand why you aren't running the test I asked for and providing the output. I can't help you if you won't assist in diagnosing the issue.

**Comment by unotech001** [comment] 2017-10-23 09:58
We have not closed the Issue.

Actully we have tested as per your suggetion .The Data was replicated but if we replicate  few columns or try to use row filter the Output is still coming same that all columns are replicate.


**In the output all columns of selected table are replicated.**

**Comment by ringerc** [comment] 2017-10-23 12:54
Let me repeat what I asked for, rephrased.

Please enable 

   log_statement = 'all' 

on both nodes, then

    SELECT pg_reload_conf()

on both nodes, or restart them?

Then re-run `pglogical.alter_subscription_resynchronize_table('subcsription1','patientdtl')` ?

Now look at the log files on both nodes. Either send the full logs, or at minimum look for any `COPY` query in the logs, and add that to this discussion.

BTW:

![closed](https://user-images.githubusercontent.com/274337/31889941-1214e6ea-b834-11e7-9533-f8b0c3b224c7.png)

Reopening.

Please supply the requested logs. I cannot help you without them.

**Comment by unotech001** [comment] 2017-10-24 04:19
As per your reply please find the log files of both provider and subscriber node after performing the required steps and kindly  provide us the solution.


[Provider Log.txt](https://github.com/2ndQuadrant/pglogical/files/1409506/Provider.Log.txt)
[Subscriber Log.txt](https://github.com/2ndQuadrant/pglogical/files/1409507/Subscriber.Log.txt)

**Comment by ringerc** [comment] 2017-10-24 04:34
Thanks.

Provider:

```
LOG:  statement: SELECT i.relid, i.nspname, i.relname, i.att_list,       i.has_row_filter  FROM pglogical.show_repset_table_info('"public"."patientdtl"'::regclass, ARRAY['default','default_insert_only','ddl_sql']) i
LOG:  statement: COPY "public"."patientdtl" (pat_id,pat_name,pat_age) TO stdout
```

What's the output if you run

    SELECT i.relid, i.nspname, i.relname, i.att_list,       i.has_row_filter
    FROM pglogical.show_repset_table_info('"public"."patientdtl"'::regclass, 
             ARRAY['default','default_insert_only','ddl_sql']) i

manually on the provider?

The output of 

    SELECT * FROM pglogical.TABLES where relid = 'public.patiendtl'::regclass;

would also be useful, as would

    SELECT * FROM pglogical.replication_set_table WHERE set_reloid = 'public.patiendtl'::regclass;

Hopefully that'll give me enough to work with.

**Comment by unotech001** [comment] 2017-10-24 04:55
Please find the output of your given queries:

Query: SELECT i.relid, i.nspname, i.relname, i.att_list,       i.has_row_filter
FROM pglogical.show_repset_table_info('"public"."patientdtl"'::regclass, 
         ARRAY['default','default_insert_only','ddl_sql']) i;

Output: 
relid | nspname |  relname   |         att_list          | has_row_filter
-------+---------+------------+---------------------------+----------------
 18079 | public  | patientdtl | {pat_id,pat_name,pat_age} | f

Ouery:  SELECT * FROM pglogical.TABLES where relid = 'public.patientdtl'::regclass;

Output:
 relid | nspname |  relname   |    set_name
-------+---------+------------+-----------------
 18079 | public  | patientdtl | replication_set
 18079 | public  | patientdtl | repset


Query:  SELECT * FROM pglogical.replication_set_table WHERE set_reloid = 'public.patientdtl'::regclass;

Output:
 set_id   | set_reloid |   set_att_list    |
                                                    set_row_filter

------------+------------+-------------------+-----------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------
  726052966 | patientdtl |                   | {OPEXPR :opno 521 :opfuncid 147 :opresulttype 16 :opretset false :opcollid 0 :inputcollid 0 :args ({VAR :varno 1 :varattno 1 :vart
ype 23 :vartypmod -1 :varcollid 0 :varlevelsup 0 :varnoold 1 :varoattno 1 :location 7} {CONST :consttype 23 :consttypmod -1 :constcollid 0 :constlen 4 :constbyval true :constisn
ull false :location 16 :constvalue 4 [ 2 0 0 0 0 0 0 0 ]}) :location 14}
 3582268140 | patientdtl | {pat_id,pat_name} |
(2 rows)

**Comment by ringerc** [comment] 2017-10-24 05:59
Aaah, so you have *two separate replication sets*, one of which has a row filter, and one of which has a column filter.

Was that your intention?

What's the output of `SELECT * FROM pglogical.replication_set` ?

**Comment by unotech001** [comment] 2017-10-24 06:23
Please find the ouput below for the mention query:

Query:   SELECT * FROM pglogical.replication_set

Output: 
set_id   | set_nodeid |      set_name       | replicate_insert | replicate_up
date | replicate_delete | replicate_truncate
------------+------------+---------------------+------------------+-------------
-----+------------------+--------------------
  290045701 | 2976894835 | default             | t                | t
     | t                | t
 3461245231 | 2976894835 | default_insert_only | t                | f
     | f                | t
 2465411902 | 2976894835 | ddl_sql             | t                | f
     | f                | f
 3582268140 | 2976894835 | repset              | t                | t
     | t                | t
  726052966 | 2976894835 | replication_set     | t                | t
     | t                | t

We are using the 'repset' as replication set not 'replication_set' and we are using same for row filter and column filter.

**Comment by unotech001** [comment] 2017-10-24 06:31
Also we have removed the 'replication_set' because we are not using it.

**Comment by ringerc** [comment] 2017-10-24 06:32
> We are using the 'repset' as replication set not 'replication_set' and we are using same for row filter and column filter.

That doesn't match what I see in the query output, so something odd is happening.

The table `patientdtl` is a member of two replication sets, set id `726052966` (`replication_set`), which has a row filter in `set_row_filter`. And set id `3582268140` (`repset`), which has a column-attribute filter in `set_att_list`.

So far it looks like a configuration issue.

**Comment by ringerc** [comment] 2017-10-24 06:36
Try removing the replication set from the table, then adding it back with the desired configuration.

Then re-check the above output and confirm that there is a *single* row for the table in `replication_set_table` with *both* a row and column filter. Then try resyncing the table.

**Comment by unotech001** [comment] 2017-10-24 07:23
We have create one new database 'sso' again and one table 'empdtl' and tried all steps & configuration again with new replication set names as 'rep' but same output is coming. 

Please checked the attached logs for your reference.

[Provider Log.txt](https://github.com/2ndQuadrant/pglogical/files/1409889/Provider.Log.txt)
[Subscriber Log.txt](https://github.com/2ndQuadrant/pglogical/files/1409890/Subscriber.Log.txt)

**Comment by ringerc** [comment] 2017-10-24 07:35
OK, but I can't *see* those steps and configuration. If you rebuilt it, please show the *exact* queries run to set things up, and re-run the information gathering queries from above to show the resulting state.

**Comment by unotech001** [comment] 2017-10-24 07:50
First we created 'sso' database(postgres 9.5) on both which have empdtl table contain 3 columns as above:
1.empid int primary key
2.empname char(50)
3.empage int

Now we want to replicate only pat_id and pat_age columns  on subscriber but after follow below procedure and configuration:

On provider and Subscriber need to set below parameter in postgresql.conf
wal_level = 'logical'
max_worker_processes = 10        
max_replication_slots = 10                  
max_wal_senders = 10 
log_statement = 'all'                       
shared_preload_libraries = 'pglogical'      
track_commit_timestamp = on          
also set below parameter in pg_hba.conf
host    all                  all          0.0.0.0/0           trust
host    replication     postgres     0.0.0.0/       trust

On provider :-

    CREATE EXTENSION pglogical;

    SELECT pglogical.create_node('provider1', 'host=put here provider IP  port=5432 dbname=sso user=postgres ');

3.created replication sets and add tables to them

select pglogical.create_replication_set( 'rep', true,true,true,true);

select pglogical.replication_set_add_table( 'rep','empdtl', true,columns:='{empid,empage}');

On Subscriber :-
1.CREATE EXTENSION pglogical;

2.SELECT pglogical.create_node('subscriber', 'host=put here subscriber IP port=5432 dbname=sso user=postgres ');

3.SELECT pglogical.create_subscription(subscription_name := 'subscription1', provider_dsn := 'host= privider ip port=5432 dbname=sso user=postgres', synchronize_structure := false, synchronize_data := true);

4. select pglogical.alter_subscription_resynchronize_table('subcsription1','empdtl');

After performing above all steps and configuration the desired output(column filter) is not coming. You can check the above procedure on your side and let us know.

**Comment by ringerc** [comment] 2017-10-24 07:58
I don't see anywhere where you set the subscription to recieve from the replication set `rep`.

If anything, I would expect this to have no effect, or empty the table, because you haven't added `empdtl` to the `default` replication set, either via `replication_set_add_all_tables` or `replication_set_add_table`. Nor have you told the subscriber to subscribe to the replication set `rep`.

I'd say that's the underlying problem here.

**Comment by unotech001** [comment] 2017-10-24 09:22
Please see the step no.3 in provider for replication_set_add_table and step 3 in subscriber for create subscription in previous reply.

**Comment by ringerc** [comment] 2017-10-25 07:46
There is no `replication_sets` argument to `pglogical.create_subscription`, therefore it uses the default sets `ARRAY['default', 'default_insert_only', 'ddl_sql']`.

I see that you add the table to the repset `rep`. But you don't subscribe to it.

**Comment by unotech001** [comment] 2017-10-25 09:05
Thank you so much. Finally it worked for us.
We have subscribed the repset 'rep' by query = select pglogical.alter_subscription_add_replication_set('subscription1', 'rep');   and it worked for us.
Once again Thanks Craig.

**Comment by ringerc** [comment] 2017-10-30 01:53
Not a bug, closing.

Maybe we need some documentation clarifications here.

@unotech001 It'd be wonderful if you could submit some proposed text that, if it'd been in the `README` might've helped you.

**Closed by ringerc** 2017-10-30 01:54 UTC
Labels: invalid
