### ISSUE TITLE
Down replication with no ERROR or LOG messages

### ISSUE THREAD

**Issue by jfinzel** [2ndQuadrant/pglogical#78] opened 2017-02-24 15:22 UTC
Recently, we have replication down with no explanation, and absolutely no messages in the logs with log level LOG or ERROR that correspond to the down.  In fact, disabling the subscriptions then shows status = `disabled`, and then when I enable it, it again shows status = `down`.  Really hard to troubleshoot this.  I peek at the changes and find nothing interesting.

This is a 9.5.5 provider and a 9.6.2 subscriber, but we experienced the same issue when subscriber was on 9.5.  The subscriber has multiple providers.

**Comment by jfinzel** [comment] 2017-02-24 15:37
I'm not going to close the issue, but I found out how to resolve it, which seems crazy.

I simply ran `pg_replication_origin_advance` to the very first LSN in the change stream:

```
SELECT pg_replication_origin_advance('pgl_audit_providerf9cd8b7_03d5bb','E/90C9DF58');
```

Somehow this unwedged replication issue, and it works now.

**Comment by ringerc** [comment] 2017-02-27 02:41
Interesting issue.

Did you get a chance to hook gdb up to the apply worker and/or walsender to
see what it was doing? Or reload Pg with a higher debug log level?

**Comment by DB140141** [comment] 2017-02-27 14:37
This is another one of those cases where this is only happening on a production system.  So no chance of running gdb in this situation.  I don't have the kind of time to try to reproduce it exactly in a snapshot environment, but I was curious if you have ever encountered similar behavior.

I will keep this thread up to date with any developments on this issue.

**Comment by jfinzel** [comment] 2017-02-27 14:38
^^^ That was me 😄

**Comment by ringerc** [comment] 2017-02-28 01:48
I haven't seen similar issues yet.

It's actually quite safe to attach gdb to a walsender or apply worker in
production. You can 'gcore' it and analyse the core later, though saving a
'bt full' is a good idea too.

We've recently identified some issues in the snapshot builder, but I don't
see how that'd pertain to this issue.

**Comment by ringerc** [comment] 2017-03-01 08:55
On 28 February 2017 at 23:16, Jeremy Finzel <notifications@github.com>
wrote:

> I understand that may theoretically true, but we wouldn't ever consider
> that safe in our environment. When testing on snapshots, the cluster has
> crashed several times with gdb attached to one of the apply workers. We
> will not even install gdb on a production server.
>
> In any case, I hope the snapshot builder issue will fix this issue? #64
> <https://github.com/2ndQuadrant/pglogical/issues/64>
>
>
> I doubt it; I don't see how it's likely to be related to the snapshot
builder if it was an established replication slot. But I haven't been
working closely with Petr on the snapbuild issues, so it's possible.

-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by ringerc** [comment] 2017-03-01 08:59
> When testing on snapshots, the cluster has crashed several times with gdb attached to one of the apply workers. We will not even install gdb on a production server.

Needless to say that should not happen. If you find incidents where that happens and you can get a core file from the crash or a glibc abort stack trace, please report it, at least if you're using a vaguely recent gdb and gcc.

**Comment by carbonin** [comment] 2018-03-29 19:24
@jfinzel what version of pglogical were you running when this happened?

I'm seeing this currently in a production system running version 1.2.1
It looks like the apply worker for the subscription exited cleanly and just won't restart.

We also tried to disable the subscription and re-enable with no result.

@ringerc outside of the already suggested gdb (as neither wal sender nor apply process is running) is there anything else we should look for?

**Comment by jfinzel** [comment] 2018-03-29 20:35
@carbonin Yes, I think I was on the same version.  I have usually been able to resolve this with one trick that often unwedges replication issues, which is running `VACUUM FULL pglogical.subscription` on the subscriber.  Try disabling and re-enabling replication several times. 
 Don't ask me why that has helped though.... :)

Sorry, that's about all I know.  I am 99% of the time able to get replication working again by just waiting and trying above things...  I also have done `pg_replication_origin_advance` to the same position as noted above.

**Comment by carbonin** [comment] 2018-03-29 21:44
Thanks, @jfinzel we were able to get things working again, but not sure what did it.

We tried the `pg_replication_origin_advance` but it didn't seem to do anything at the time. Some time after that the four `down` subscriptions starting coming back.

**Comment by eulerto** [comment] 2021-04-19 22:31
Since it is an ancient version and there are not log messages or stack trace, I'm closing this issue. If it still happens with the latest pglogical version, open a new issue (hopefully with information to help in the investigation).

**Closed by eulerto** 2021-04-19 22:31 UTC

**Comment by atsu85** [comment] 2021-09-27 15:46
@jfinzel , @carbonin for me the problem was related to schema change (colum added to a table) in replicated DB that wasn't automatically done in replica DB. Disabling & enabling subscription didn't change replication status from `down` to `replicating` before i updated the schema in replica DB and re-enabled subscription.

I knew that schema changes are not automatically applied to replica DB, but i didn't suspect it initially, because previously i had seen errors like "permission denied for schema pglogical" when developers tried to change DB schema after replication was set up - i guess only some schema changes (like `drop`) need permissions for pglogical schema and others (like adding column) don't need them
