### ISSUE TITLE
Error "attempted to lock invisible tuple" when performing BEFORE UPDATE trigger on subscriber

### ISSUE THREAD

**Issue by Jelle1** [2ndQuadrant/pglogical#97] opened 2017-05-09 20:05 UTC
Hi,

I'd like to know if this is a bug or if I'm doing something wrong.

I am running PostgreSQL 9.5 and pglogical 1.2.1. Replication crashes and PostgreSQL's logs are reporting

> LOG:  starting apply for subscription subscription2
> ERROR:  attempted to lock invisible tuple
> LOG:  apply worker [15051] at slot 1 generation 40 crashed
> LOG:  worker process: pglogical apply 16384:1871150101 (PID 15051) exited with exit code 1

CREATE TABLE public.test ( id integer primary key, name text );

CREATE OR REPLACE FUNCTION no_op() RETURNS TRIGGER AS
$$
BEGIN
  RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER perform_no_op
   BEFORE UPDATE ON public.test
   FOR EACH ROW
   EXECUTE PROCEDURE no_op();

ALTER TABLE public.test ENABLE REPLICA TRIGGER perform_no_op;

and then on the provider run

BEGIN;
INSERT INTO test (id, name) VALUES (1, 'one');
UPDATE test SET name = 'one_updated' WHERE id = 1;
COMMIT;

I'm trying to use a BEFORE UPDATE trigger to audit the changes made by replication.

Help is much appreciated,

Thanks

...Jelle

Addition config:

> wal_level = 'logical'
> max_worker_processes = 10
> max_replication_slots = 10
> max_wal_senders = 10
> wal_sender_timeout = 0
> wal_receiver_timeout = 0
> track_commit_timestamp = on
> pglogical.conflict_resolution = apply_remote

**Comment by Jelle1** [comment] 2017-05-10 20:32
My workaround is to use an AFTER UPDATE trigger instead, which seems to work fine.

**Comment by PJMODOS** [comment] 2017-10-09 21:33
This should be now fixed (in 2.1).

**Closed by PJMODOS** 2017-10-09 21:33 UTC

**Comment by nrkowalski** [comment] 2018-02-21 18:29
I can confirm the issue is still present.

**Comment by ringerc** [comment] 2018-02-22 03:08
I've also seen related

"tuple concurrently modified"

errors in 2.1.1. So something's still lurking.
