### ISSUE TITLE
pglogical inserted into search_path?

### ISSUE THREAD

**Issue by chuinker** [2ndQuadrant/pglogical#57] opened 2016-11-08 01:33 UTC
1. Create an unprivileged user on a database that has pglogical installed.
2. Connect as that user.
3. Create a temporary table.
4. Attempt to drop temporary table.
5. Despair.

```
$ psql -h localhost -d test -U joenobody -W
Password for user joenobody:
psql (9.6.0)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

test=> create temporary table x (y integer);
CREATE TABLE
test=> drop table if exists x;
ERROR:  permission denied for schema pglogical
test=> show search_path;
   search_path
-----------------
 "$user", public
(1 row)
```

**Comment by chuinker** [comment] 2016-11-08 01:37
`GRANT USAGE ON pglogical to joenobody;` fixes the issue.

**Comment by ringerc** [comment] 2016-11-08 03:31
I suspect this relates to truncate triggers and the fact that the command
filter doesn't know it's a temp table by looking at the DROP statement
alone. We might need to bypass permissions checks somewhere.

Can you re-run with

\set verbosity verbose

?

**Comment by coreyatmoat** [comment] 2016-11-08 15:48
That yielded no new information.

```
$ psql -h localhost -d test -U joenobody -W
Password for user joenobody:
psql (9.6.0)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

test=> \set verbosity verbose
test=> create temporary table x(y integer);
CREATE TABLE
test=> drop table if exists x;
ERROR:  permission denied for schema pglogical
test=>
```

**Comment by PJMODOS** [comment] 2016-11-12 09:31
This is duplicate of #15

**Closed by PJMODOS** 2016-11-12 09:31 UTC
Labels: duplicate

**Comment by chuinker** [comment] 2016-11-12 15:56
I think you should reconsider fixing this bug.

As it is now, if I install pglogical on a database, then any existing code which creates a temporary table WILL FAIL until such time as I grant USAGE on SCHEMA pglogical to public. If that grant happens inside the CREATE EXTENSION, that's fine, but installing an extension should never break code that doesn't even reference the extension.
